### ISSUE TITLE
 cannot resolve class 'LocaleQueryData' from 'FlutterNewsStrings'

### ISSUE THREAD

**Issue by zilongc** [andresaraujo/flutter_news#15]
Launching lib\main.dart on MI 6 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Error: 'package:flutter_news/fnews_strings.dart': malformed type: line 12 pos 34: cannot resolve class 'LocaleQueryData' from 'FlutterNewsStrings'
class FlutterNewsStrings extends LocaleQueryData {
                                 ^
Failed to run the Flutter compiler. Exit code: 254

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 329

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command 'D:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 254

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Finished with error: Gradle build failed: 1

**Comment by leoybkim** [comment]
@zilongc I looked into the issue and the problem was due to deprecation of `LocaleQuery` `LocalQueryData` classes [#11497](https://github.com/flutter/flutter/pull/11497). Please check the pull request I made in #16. You can also checkout from my [fork](https://github.com/leoybkim/flutter_news).

**Comment by andresaraujo** [comment]
Thanks @zilongc @leoybkim 

This is fixed in commit 75e7c1ee5a8450df35986d5cf3264bebc8ebb718
